version: "3"

services:

  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    ports:
      - 4444:4444

  application:
    build: ./
    depends_on:
      - chrome
    environment:
      - REMOTE_HOST=http://chrome:4444
      - TARGET_URL=https://tiktok.com/@caseyjohnsonwv